[package]
name = "shuttle-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = {workspace=true}
anyhow = {workspace=true}
tokio = {workspace=true}
socks5-proto = "0.4.0"
