name: release-build

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Run tests
        run: cargo test --verbose
  cross:
    needs: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            name: shuttle-x86_64-unknown-linux-musl.tgz
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            name: shuttle-aarch64-unknown-linux-musl.tgz
          - os: ubuntu-latest
            target: i686-unknown-linux-musl
            name: shuttle-i686-unknown-linux-musl.tgz

          - os: macOS-latest
            target: x86_64-apple-darwin
            name: shuttle-x86_64-apple-darwin.tgz
          - os: macOS-latest
            target: aarch64-apple-darwin
            name: shuttle-aarch64-apple-darwin.tgz


          - os: windows-latest
            target: x86_64-pc-windows-msvc
            name: shuttle-x86_64-pc-windows-msvc.zip
          - os: windows-latest
            target: i686-pc-windows-msvc
            name: shuttle-i686-pc-windows-msvc.zip


    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: full
    continue-on-error: true
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true
          profile: minimal
          target: ${{ matrix.target }}

      - name: Install GNU tar
        if: matrix.target == 'aarch64-apple-darwin'
        run: |
          brew install gnu-tar
          # echo "::add-path::/usr/local/opt/gnu-tar/libexec/gnubin"
          echo "/usr/local/opt/gnu-tar/libexec/gnubin" >> $GITHUB_PATH

      # https://github.com/actions/virtual-environments/issues/2557#issuecomment-769611326
      - name: Build | Build for aarch64 apple
        if: matrix.target == 'aarch64-apple-darwin'
        run: |
          sudo xcode-select -s /Applications/Xcode_12.4.app &&
          sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*
          cargo build --release --features "local-redir local-tun armv8 neon"  --target "${{ matrix.target }}"

      - name: Build | Build
        if: matrix.target != 'aarch64-apple-darwin'
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
          use-cross: true

      - name: Post Build | Prepare artifacts [Windows]
        if: matrix.os == 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          xcopy ../../../examples/* examples
          strip shuttles.exe
          strip shuttlec.exe
          7z a ../../../${{ matrix.name }} shuttles.exe shuttlec.exe examples/*
          cd -
      - name: Post Build | Prepare artifacts [unix]
        if: matrix.os != 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          cp ../../../examples/* examples
          strip shuttles && strip shuttlec || true
          tar czvf ../../../${{ matrix.name }} shuttles shuttlec examples/*
          cd -

      - name: Deploy | Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.name }}
          generate_release_notes: true
          prerelease: true
          token: ${{ secrets.SHUTTLE_GITHUB_TOKEN }}
